import { Movie } from "./types";

export const MOVIES_DATA: Movie[] = [
  {
    id: "interstellar",
    title: "Interestelar",
    originalTitle: "Interstellar",
    year: 2014,
    duration: "2h 49m",
    rating: 8.7,
    genres: ["Ficção Científica", "Drama", "Aventura"],
    synopsis: "As reservas naturais da Terra estão se esgotando e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie humana. Cooper é chamado para liderar o grupo e aceita a missão sabendo que pode nunca mais ver seus filhos.",
    backdropUrl: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "zSWdZVtXT7E",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    director: "Christopher Nolan",
    featured: true,
    type: "filme",
    imdbId: "tt0816692"
  },
  {
    id: "inception",
    title: "A Origem",
    originalTitle: "Inception",
    year: 2010,
    duration: "2h 28m",
    rating: 8.8,
    genres: ["Ficção Científica", "Ação", "Suspense"],
    synopsis: "Dom Cobb é um ladrão habilidoso, o melhor na perigosa arte da extração: roubar segredos valiosos do fundo do subconsciente durante o estado de sono, quando a mente está mais vulnerável. A rara habilidade de Cobb fez dele um jogador cobiçado no mundo da espionagem corporativa, mas também o tornou um fugitivo internacional.",
    backdropUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "YoHD9XEInc0",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
    director: "Christopher Nolan",
    featured: false,
    type: "filme",
    imdbId: "tt1375666"
  },
  {
    id: "dune2",
    title: "Duna: Parte Dois",
    originalTitle: "Dune: Part Two",
    year: 2024,
    duration: "2h 46m",
    rating: 8.9,
    genres: ["Ficção Científica", "Aventura", "Ação"],
    synopsis: "Paul Atreides se une a Chani e aos Fremen enquanto busca vingança contra os conspiradores que destruíram sua família. Enfrentando uma escolha entre o amor de sua vida e o destino do universo, ele se esforça para evitar um futuro terrível que só ele pode prever.",
    backdropUrl: "https://images.unsplash.com/photo-1547483238-f400e65ccd56?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "Way9Dexny3w",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Austin Butler", "Florence Pugh"],
    director: "Denis Villeneuve",
    featured: true,
    type: "filme",
    imdbId: "tt15239678"
  },
  {
    id: "spiderverse",
    title: "Homem-Aranha: Através do Aranhaverso",
    originalTitle: "Spider-Man: Across the Spider-Verse",
    year: 2023,
    duration: "2h 20m",
    rating: 8.6,
    genres: ["Animação", "Ação", "Aventura"],
    synopsis: "Depois de se reunir com Gwen Stacy, Miles Morales, o amigão da vizinhança do Brooklyn, é catapultado através do Multiverso, onde ele encontra uma equipe de Pessoas-Aranha encarregadas de proteger sua própria existência. Mas quando os heróis colidem sobre como lidar com uma nova ameaça, Miles se vê confrontado com as outras Aranhas.",
    backdropUrl: "https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1608889174633-41a0c2439401?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "shW9i6k8cB0",
    cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac", "Jake Johnson"],
    director: "Joaquim Dos Santos",
    featured: false,
    type: "filme",
    imdbId: "tt9362722"
  },
  {
    id: "darkknight",
    title: "Batman: O Cavaleiro das Trevas",
    originalTitle: "The Dark Knight",
    year: 2008,
    duration: "2h 32m",
    rating: 9.0,
    genres: ["Ação", "Policial", "Drama"],
    synopsis: "Com a ajuda de Jim Gordon e Harvey Dent, Batman tem mantido a ordem na cidade de Gotham. Mas um jovem e brilhante criminoso conhecido como Coringa chega para instaurar o caos absoluto e testar os limites morais do Cavaleiro das Trevas.",
    backdropUrl: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "EXeTwQWrcwY",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Maggie Gyllenhaal"],
    director: "Christopher Nolan",
    featured: true,
    type: "filme",
    imdbId: "tt0468569"
  },
  {
    id: "cidadededeus",
    title: "Cidade de Deus",
    originalTitle: "City of God",
    year: 2002,
    duration: "2h 10m",
    rating: 8.6,
    genres: ["Policial", "Drama"],
    synopsis: "Buscapé é um jovem pobre, negro e muito sensível, que cresce em um universo de muita violência. Buscapé vive na Cidade de Deus, favela carioca conhecida por ser um dos locais mais violentos do Rio. Acuado pelo roubo e tráfico, ele descobre seu talento como fotógrafo profissional.",
    backdropUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "dcUOO4ytIsc",
    cast: ["Alexandre Rodrigues", "Leandro Firmino", "Phellipe Haagensen", "Douglas Silva"],
    director: "Fernando Meirelles",
    featured: false,
    type: "filme",
    imdbId: "tt0317248"
  },
  {
    id: "spiritedaway",
    title: "A Viagem de Chihiro",
    originalTitle: "Sen to Chihiro no Kamikakushi",
    year: 2001,
    duration: "2h 5m",
    rating: 8.6,
    genres: ["Animação", "Fantasia", "Família"],
    synopsis: "Chihiro, uma menina de 10 anos, está se mudando com os pais. No caminho, o pai pega um atalho e eles chegam a um túnel que leva a um parque de diversões abandonado. Os pais encontram comida deliciosa e começam a comer, mas se transformam em porcos. Chihiro agora precisa salvar seus pais de um mundo místico de espíritos.",
    backdropUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "ByXuk9QqQkk",
    cast: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"],
    director: "Hayao Miyazaki",
    featured: false,
    type: "filme",
    imdbId: "tt0245429"
  },
  {
    id: "insideout2",
    title: "Divertida Mente 2",
    originalTitle: "Inside Out 2",
    year: 2024,
    duration: "1h 36m",
    rating: 8.0,
    genres: ["Animação", "Família", "Comédia"],
    synopsis: "Divertida Mente 2, da Disney e da Pixar, volta a entrar na mente da agora adolescente Riley, mesmo no momento em que o Quartel General está a passar por uma demolição repentina para dar lugar a algo totalmente inesperado: novas Emoções! Alegria, Tristeza, Raiva, Medo e Repulsa não sabem como reagir quando a Ansiedade aparece.",
    backdropUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "L4D5McGD_oc",
    cast: ["Amy Poehler", "Maya Hawke", "Phyllis Smith", "Lewis Black"],
    director: "Kelsey Mann",
    featured: false,
    type: "filme",
    imdbId: "tt22022454"
  },
  {
    id: "matrix",
    title: "Matrix",
    originalTitle: "The Matrix",
    year: 1999,
    duration: "2h 16m",
    rating: 8.7,
    genres: ["Ficção Científica", "Ação"],
    synopsis: "O jovem programador Thomas Anderson é atormentado por estranhos pesadelos em que está conectado por cabos a um computador gigante. À medida que o sonho se repete, ele começa a desconfiar da realidade. Ele encontra os misteriosos Morpheus e Trinity e descobre que é vítima do Matrix, um sistema inteligente e artificial que manipula as mentes.",
    backdropUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "vKQi3bBA1y8",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
    director: "Lana Wachowski, Lilly Wachowski",
    featured: false,
    type: "filme",
    imdbId: "tt0133093"
  },
  // SERIES
  {
    id: "breakingbad",
    title: "Breaking Bad",
    originalTitle: "Breaking Bad",
    year: 2008,
    duration: "5 Temps",
    rating: 9.5,
    genres: ["Drama", "Policial"],
    synopsis: "Um professor de química do ensino médio diagnosticado com câncer de pulmão inoperável se volta para a fabricação e venda de metanfetamina com um ex-aluno para garantir o futuro financeiro de sua família, transformando-se gradualmente no temido Heisenberg.",
    backdropUrl: "https://images.unsplash.com/photo-1533488765986-dfa2a9939acd?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "HhesaQXLuRY",
    cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Bob Odenkirk"],
    director: "Vince Gilligan",
    featured: true,
    type: "serie",
    imdbId: "tt0903747"
  },
  {
    id: "strangerthings",
    title: "Stranger Things",
    originalTitle: "Stranger Things",
    year: 2016,
    duration: "4 Temps",
    rating: 8.7,
    genres: ["Ficção Científica", "Suspense", "Drama"],
    synopsis: "Quando um garoto desaparece no nada de uma pequena cidade pacata, sua mãe, o chefe de polícia e um carismático grupo de amigos precisam enfrentar forças sobrenaturais e terríveis experimentos do governo para trazê-lo de volta, descobrindo o Mundo Invertido.",
    backdropUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1568832359672-e36cf5d74f54?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "b9EkMc79ZSU",
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour"],
    director: "The Duffer Brothers",
    featured: false,
    type: "serie",
    imdbId: "tt4574334"
  },
  {
    id: "wednesday",
    title: "Wandinha",
    originalTitle: "Wednesday",
    year: 2022,
    duration: "1 Temp",
    rating: 8.1,
    genres: ["Comédia", "Fantasia", "Suspense"],
    synopsis: "Inteligente, sarcástica e um pouco morta por dentro, Wandinha Addams investiga uma onda de assassinatos sobrenaturais enquanto faz novos amigos — e inimigos — na Academia Nunca Mais, lidando com seus próprios poderes psíquicos recém-descobertos.",
    backdropUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "Di310WS8zLk",
    cast: ["Jenna Ortega", "Gwendoline Christie", "Riki Lindhome", "Christina Ricci"],
    director: "Tim Burton",
    featured: false,
    type: "serie",
    imdbId: "tt13443470"
  },
  // ANIMES
  {
    id: "narutoshippuden",
    title: "Naruto Shippuden",
    originalTitle: "Naruto: Shippûden",
    year: 2007,
    duration: "21 Temps",
    rating: 8.7,
    genres: ["Animação", "Ação", "Aventura"],
    synopsis: "Naruto Uzumaki retorna à Vila Oculta da Folha após anos de treinamento com Jiraiya. Ele deve enfrentar novos e poderosos vilões da organização criminosa Akatsuki enquanto busca salvar seu amigo Sasuke Uchiha e alcançar seu sonho de se tornar o Hokage.",
    backdropUrl: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "1y_v9f8pInQ",
    cast: ["Junko Takeuchi", "Noriaki Sugiyama", "Chie Nakamura"],
    director: "Hayato Date",
    featured: true,
    type: "anime",
    imdbId: "tt0988824"
  },
  {
    id: "attackontitan",
    title: "Attack on Titan",
    originalTitle: "Shingeki no Kyojin",
    year: 2013,
    duration: "4 Temps",
    rating: 9.1,
    genres: ["Animação", "Ação", "Aventura", "Fantasia"],
    synopsis: "A humanidade vive em cidades cercadas por enormes muralhas devido à aparição repentina dos Titãs, criaturas gigantescas sem inteligência aparente que devoram humanos. Eren Yeager e seus amigos juntam-se à tropa de exploração de elite para combatê-los.",
    backdropUrl: "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "MGRm4IzK1SQ",
    cast: ["Yuki Kaji", "Yui Ishikawa", "Marina Inoue"],
    director: "Tetsurō Araki",
    featured: false,
    type: "anime",
    imdbId: "tt2560140"
  },
  {
    id: "deathnote",
    title: "Death Note",
    originalTitle: "Death Note",
    year: 2006,
    duration: "1 Temp",
    rating: 9.0,
    genres: ["Animação", "Policial", "Drama", "Suspense"],
    synopsis: "Um estudante do ensino médio brilhante mas entediado encontra um caderno sobrenatural que lhe dá o poder de matar qualquer pessoa escrevendo seu nome nele. Ele decide expurgar o mal do mundo enquanto um detetive excêntrico e genial tenta desmascará-lo.",
    backdropUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "NlJZ-YgAt-c",
    cast: ["Mamoru Miyano", "Kappei Yamaguchi", "Shidou Nakamura"],
    director: "Tetsurō Araki",
    featured: false,
    type: "anime",
    imdbId: "tt0877057"
  },
  {
    id: "onepiece",
    title: "One Piece",
    originalTitle: "One Piece",
    year: 1999,
    duration: "20+ Temps",
    rating: 8.9,
    genres: ["Animação", "Ação", "Aventura", "Fantasia"],
    synopsis: "Monkey D. Luffy, um jovem que ganhou propriedades elásticas após comer uma Fruta do Diabo, navega pelos mares com sua valente tripulação dos Chapéus de Palha em busca do lendário tesouro supremo, o One Piece, para tornar-se o próximo Rei dos Piratas.",
    backdropUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=1200",
    posterUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=500",
    trailerVideoId: "S8_YwFLCh4U",
    cast: ["Mayumi Tanaka", "Tony Beck", "Laurent Vernin"],
    director: "Tatsuya Nagamine",
    featured: false,
    type: "anime",
    imdbId: "tt1122718"
  }
];
